apiVersion: apps/v1beta2 # before 1.9
kind: Deployment
metadata:
  name: eth-node
spec:
  selector:
    matchLabels:
      app: eth-node
  replicas: 1
  template:
    metadata:
      labels:
        app: eth-node
    spec:
      containers:
      - name: eth-node
        image: matthewberryhill/shapeshift-eth-node:latest
